[tox]
envlist =
    py39
    py310
    py311
    py312
    py313
    py314

[testenv]
commands = pytest tests/ --cov {posargs} 
setenv =
    COVERAGE_FILE={envdir}/.coverage.{envname}
    COVERAGE_RCFILE={toxinidir}/tox.ini
deps =
    pytest
    pytest-cov
    boto3

[coverage:run]
branch = True
source = newrelic_lambda
omit =
    **/_version.py

[coverage:paths]
source =
    src/newrelic_lambda/
    .tox/**/site-packages/newrelic_lambda/
    /__w/**/site-packages/newrelic_lambda/
    /home/runner/**/src/newrelic_lambda/

[coverage:html]
directory = ${TOX_ENV_DIR-.}/htmlcov

[coverage:xml]
output = ${TOX_ENV_DIR-.}/coverage.xml
